[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.39.0",
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
pythonpath = ["./src"]
addopts = "-ra -q"
testpaths = [
    "tests",
]